version: '3'
services:
  backend:
    image: scores-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3200:3000
    container_name: scores-backend
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
